//! Deterministic ML-DSA-65 known-answer and cross-implementation vectors.
//!
//! The fixture at `tests/vectors/ml_dsa65_v1.json` is generated by Rust's
//! `fips204` implementation and consumed by the Worker's
//! `@noble/post-quantum` verification test. This is the production direction:
//! the WASM client signs and the Worker verifies.
//!
//! Regenerate only after deliberately reviewing an ML-DSA implementation or
//! signature-preimage change:
//!
//! ```text
//! QUB_REGEN_VECTORS=1 cargo test -p qub-core --test ml_dsa65_vectors
//! ```

use std::fs;
use std::path::PathBuf;

use fips204::ml_dsa_65;
use fips204::traits::{KeyGen, SerDes, Signer};
use qub_core::signing::{compute_sig_input, compute_sig_input_v2, verify};

const REGEN_ENV_VAR: &str = "QUB_REGEN_VECTORS";

fn vectors_path() -> PathBuf {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("tests/vectors/ml_dsa65_v1.json");
    path
}

fn sig_input_for_case(name: &str) -> [u8; 32] {
    match name {
        // V1 is retained as a primitive-compatibility vector only. Production
        // envelope verification deliberately rejects this retired preimage.
        "legacy-v1-preimage" => compute_sig_input(1, &[0x11; 32], &[0x22; 32], 1_800_000_000),
        "production-v2-preimage" => compute_sig_input_v2(
            1,
            &[0x33; 32],
            &[0x44; 32],
            1_900_000_000,
            Some("cafe\u{0301}"),
            Some(&[0x55; 32]),
        ),
        other => panic!("unknown ML-DSA-65 vector case {other:?}"),
    }
}

fn decode_fixed<const N: usize>(value: &serde_json::Value, field: &str) -> [u8; N] {
    let encoded = value
        .as_str()
        .unwrap_or_else(|| panic!("{field} must be a hex string"));
    let bytes = hex::decode(encoded).unwrap_or_else(|_| panic!("{field} must contain valid hex"));
    bytes
        .try_into()
        .unwrap_or_else(|v: Vec<u8>| panic!("{field} must be {N} bytes, got {}", v.len()))
}

#[test]
#[cfg_attr(
    miri,
    ignore = "interprets safe ML-DSA / BLS12-381 code for minutes; see MIRI_CRYPTO in docs/TESTING-FRAMEWORK.md"
)]
fn rust_signatures_match_shared_known_answer_vectors() {
    let path = vectors_path();
    let raw = fs::read_to_string(&path).expect("read ML-DSA-65 vector fixture");
    let mut fixture: serde_json::Value =
        serde_json::from_str(&raw).expect("parse ML-DSA-65 vector fixture");
    let regenerate = std::env::var(REGEN_ENV_VAR).is_ok();
    let cases = fixture["cases"]
        .as_array_mut()
        .expect("ML-DSA-65 fixture `cases` must be an array");
    assert!(!cases.is_empty(), "ML-DSA-65 fixture must contain cases");

    for case in cases {
        let name = case["name"]
            .as_str()
            .expect("ML-DSA-65 vector case must have a name")
            .to_owned();
        let keygen_seed = decode_fixed::<32>(&case["keygen_seed_hex"], "keygen_seed_hex");
        let signing_seed = decode_fixed::<32>(&case["signing_seed_hex"], "signing_seed_hex");
        let sig_input = sig_input_for_case(&name);

        let (public_key, secret_key) = ml_dsa_65::KG::keygen_from_seed(&keygen_seed);
        let signature = secret_key
            .try_sign_with_seed(&signing_seed, &sig_input, &[])
            .unwrap_or_else(|error| panic!("case {name}: seeded signing failed: {error}"));
        let public_key_bytes = public_key.into_bytes();

        if regenerate {
            case["public_key_hex"] = serde_json::Value::String(hex::encode(public_key_bytes));
            case["sig_input_hex"] = serde_json::Value::String(hex::encode(sig_input));
            case["signature_hex"] = serde_json::Value::String(hex::encode(signature));
        } else {
            let expected_public_key =
                decode_fixed::<{ ml_dsa_65::PK_LEN }>(&case["public_key_hex"], "public_key_hex");
            let expected_sig_input = decode_fixed::<32>(&case["sig_input_hex"], "sig_input_hex");
            let expected_signature =
                decode_fixed::<{ ml_dsa_65::SIG_LEN }>(&case["signature_hex"], "signature_hex");

            assert_eq!(
                public_key_bytes, expected_public_key,
                "case {name}: seeded public key changed"
            );
            assert_eq!(
                sig_input, expected_sig_input,
                "case {name}: signature preimage digest changed"
            );
            assert_eq!(
                signature, expected_signature,
                "case {name}: seeded signature bytes changed"
            );
        }

        assert!(
            verify(&public_key_bytes, &sig_input, &signature).expect("well-formed vector"),
            "case {name}: Rust rejected its pinned signature"
        );
        let mut tampered_signature = signature;
        tampered_signature[0] ^= 0x01;
        assert!(
            !verify(&public_key_bytes, &sig_input, &tampered_signature)
                .expect("well-formed tampered vector"),
            "case {name}: Rust accepted a tampered signature"
        );
    }

    if regenerate {
        let rendered = serde_json::to_string_pretty(&fixture).expect("serialise vectors fixture");
        fs::write(&path, format!("{rendered}\n")).expect("write ML-DSA-65 vector fixture");
    }
}
